# This is a placeholder so actions won't default to a getting started page

name: Placeholder

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Inicializar_repo"]
    types:
      - completed

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
